# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

<#
.SYNOPSIS
    Emits test conversation results in a prettified format to GitHub Actions.

.DESCRIPTION
    This script reads the test-conversations.json file generated by the E2E tests
    and outputs a formatted table showing prompts, responses, pass/fail status,
    and any error messages. The output is written to both console and GitHub
    Actions step summary.

.PARAMETER TestResultsDir
    The directory containing the test-conversations.json file

.EXAMPLE
    .\Emit-TestConversations.ps1 -TestResultsDir "$env:RUNNER_TEMP/TestConversations"
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$TestResultsDir
)

$ErrorActionPreference = 'Continue'

Write-Host "=== Test Conversations Report ===" -ForegroundColor Cyan
Write-Host "Results Directory: $TestResultsDir" -ForegroundColor Gray
Write-Host ""

$jsonPath = Join-Path $TestResultsDir "test-conversations.json"

if (-not (Test-Path $jsonPath)) {
    Write-Host "No test-conversations.json found at $jsonPath" -ForegroundColor Yellow
    Write-Host "This may indicate tests did not run or did not record conversations." -ForegroundColor Yellow
    exit 0
}

try {
    $results = Get-Content $jsonPath -Raw | ConvertFrom-Json
}
catch {
    Write-Host "Failed to parse test-conversations.json: $_" -ForegroundColor Red
    exit 1
}

# Console output
Write-Host ""
Write-Host "Summary:" -ForegroundColor Green
Write-Host "  Total Tests: $($results.TotalTests)"
Write-Host "  Passed: $($results.PassedTests)" -ForegroundColor Green
Write-Host "  Failed: $($results.FailedTests)" -ForegroundColor $(if ($results.FailedTests -gt 0) { 'Red' } else { 'Green' })
Write-Host "  Generated At: $($results.GeneratedAt)"
Write-Host ""

# Detailed console output
Write-Host "Test Details:" -ForegroundColor Yellow
Write-Host ("-" * 80)

foreach ($conv in $results.Conversations) {
    $statusIcon = if ($conv.Passed) { "✅" } else { "❌" }
    $statusColor = if ($conv.Passed) { "Green" } else { "Red" }
    
    Write-Host ""
    Write-Host "$statusIcon $($conv.TestName)" -ForegroundColor $statusColor
    Write-Host "   Duration: $($conv.Duration)"
    
    foreach ($turn in $conv.Turns) {
        $promptPreview = if ($turn.UserMessage.Length -gt 60) { 
            $turn.UserMessage.Substring(0, 60) + "..." 
        } else { 
            $turn.UserMessage 
        }
        
        $responsePreview = if ($turn.AgentResponse) {
            if ($turn.AgentResponse.Length -gt 80) {
                $turn.AgentResponse.Substring(0, 80) + "..."
            } else {
                $turn.AgentResponse
            }
        } else {
            "(no response)"
        }
        
        Write-Host "   Prompt: $promptPreview" -ForegroundColor Cyan
        Write-Host "   Response: $responsePreview" -ForegroundColor Gray
    }
    
    if (-not $conv.Passed -and $conv.ErrorMessage) {
        Write-Host "   Error: $($conv.ErrorMessage)" -ForegroundColor Red
    }
}

Write-Host ""
Write-Host ("-" * 80)

# GitHub Actions Step Summary
if ($env:GITHUB_STEP_SUMMARY) {
    Write-Host "Writing to GitHub Step Summary..." -ForegroundColor Gray
    
    $passedIcon = if ($results.FailedTests -eq 0) { "✅" } else { "⚠️" }
    
    $summary = @"
## $passedIcon Test Conversations Report

**Summary:** $($results.PassedTests)/$($results.TotalTests) tests passed

| Test | Status | Prompt | Response | Duration | Error |
|------|--------|--------|----------|----------|-------|
"@
    
    foreach ($conv in $results.Conversations) {
        $statusIcon = if ($conv.Passed) { "✅ Pass" } else { "❌ Fail" }
        
        foreach ($turn in $conv.Turns) {
            # Escape pipe characters and limit length for markdown table
            $promptDisplay = $turn.UserMessage -replace '\|', '\|' -replace '\n', ' '
            if ($promptDisplay.Length -gt 50) {
                $promptDisplay = $promptDisplay.Substring(0, 47) + "..."
            }
            
            $responseDisplay = if ($turn.AgentResponse) {
                $resp = $turn.AgentResponse -replace '\|', '\|' -replace '\n', ' '
                if ($resp.Length -gt 60) {
                    $resp.Substring(0, 57) + "..."
                } else {
                    $resp
                }
            } else {
                "_(no response)_"
            }
            
            $durationDisplay = if ($conv.Duration) {
                # Parse duration string and format
                $conv.Duration -replace '00:00:', '' -replace '(\d+\.\d{2})\d+', '$1s'
            } else {
                "-"
            }
            
            $errorDisplay = if ($conv.ErrorMessage) {
                $err = $conv.ErrorMessage -replace '\|', '\|' -replace '\n', ' '
                if ($err.Length -gt 40) {
                    $err.Substring(0, 37) + "..."
                } else {
                    $err
                }
            } else {
                "-"
            }
            
            $summary += "`n| $($conv.TestName) | $statusIcon | $promptDisplay | $responseDisplay | $durationDisplay | $errorDisplay |"
        }
    }
    
    # Add expandable details section for full responses
    $summary += @"

<details>
<summary>📝 Full Test Details (click to expand)</summary>

"@
    
    foreach ($conv in $results.Conversations) {
        $statusIcon = if ($conv.Passed) { "✅" } else { "❌" }
        
        $summary += @"

### $statusIcon $($conv.TestName)

- **Status:** $(if ($conv.Passed) { 'Passed' } else { 'Failed' })
- **Duration:** $($conv.Duration)
- **Timestamp:** $($conv.Timestamp)

"@
        
        $turnNum = 1
        foreach ($turn in $conv.Turns) {
            $summary += @"
**Turn $turnNum:**
- **Prompt:** ``$($turn.UserMessage)``
- **Response:** 
``````
$($turn.AgentResponse ?? '(no response)')
``````

"@
            $turnNum++
        }
        
        if (-not $conv.Passed -and $conv.ErrorMessage) {
            $summary += @"
> ⚠️ **Error:** $($conv.ErrorMessage)

"@
        }
    }
    
    $summary += @"
</details>
"@
    
    $summary | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
    Write-Host "Step summary written successfully" -ForegroundColor Green
}

# Return exit code based on test results
if ($results.FailedTests -gt 0) {
    Write-Host ""
    Write-Host "⚠️ $($results.FailedTests) test(s) failed" -ForegroundColor Yellow
}
else {
    Write-Host ""
    Write-Host "✅ All tests passed!" -ForegroundColor Green
}
