# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: CI - Build Node.js Vercel SDK Sample Agent

on:
  workflow_call:  # Called by orchestrator
  workflow_dispatch:  # Manual trigger

jobs:
  nodejs-vercelsdk-sampleagent:
    name: Node.js Vercel SDK Sample Agent
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nodejs/vercel-sdk/sample-agent

    strategy:
      matrix:
        node-version: ['18', '20']

    steps:
    - name: Checkout repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
